version: '2'
services:
   pyramid:
     build:
        context: ./
        dockerfile: ./Dockerfile 
     working_dir: /app
     ports:
        - '81:81'
     volumes:
       - './docker/base/:/app'
     environment:
       - PATHS_FROM_ECLIPSE_TO_PYTHON=[["C:/Users/diogo/Developer/python/python_container/docker/base","/app"]]

